version: '3.0'

services:
  app-container:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  data-extract-container:
    image: apache/airflow:2.10.0-python3.10
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow-data:/var/tmp
    ports:
      - 8080:8080
    command: bash -c '(airflow db init && airflow users create --username admin --password admin --firstname Nguyen --lastname Hieu --role Admin --email hieu1231411@gmail.com); airflow webserver & airflow scheduler'
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
volumes:
  dags:
  airflow-data: